"""add recommend column to reports

Revision ID: aea6a1f5497f
Revises: bfc3f018600f
Create Date: 2026-04-29 16:14:59.376642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea6a1f5497f'
down_revision: Union[str, None] = 'bfc3f018600f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('recommend', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'recommend')
    # ### end Alembic commands ###
